# Generated by Django 3.2 on 2021-04-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id_or_passport_no', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Negative', 'Negative'), ('Positive', 'Positive')], default='Negative', max_length=20)),
                ('contact', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('date_immunized', models.DateField()),
                ('report_back_date', models.DateField()),
                ('dose_status', models.CharField(choices=[('First Dose', 'First Dose'), ('Second Dose', 'Second Dose')], default='First Dose', max_length=20)),
            ],
        ),
    ]
